# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopping_cart.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shopping_cart.proto',
  package='org.ffsf.demo.shoppingcart',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13shopping_cart.proto\x12\x1aorg.ffsf.demo.shoppingcart\"\xda\x01\n\tCartEvent\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12<\n\x0b\x61\x64\x64_to_cart\x18\x02 \x01(\x0b\x32%.org.ffsf.demo.shoppingcart.AddToCartH\x00\x12;\n\nclear_cart\x18\x03 \x01(\x0b\x32%.org.ffsf.demo.shoppingcart.ClearCartH\x00\x12\x38\n\x08\x63heckout\x18\x04 \x01(\x0b\x32$.org.ffsf.demo.shoppingcart.CheckoutH\x00\x42\x07\n\x05\x65vent\".\n\tAddToCart\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"\x0b\n\tClearCart\"\n\n\x08\x43heckout\"S\n\x07Receipt\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x37\n\tuser_cart\x18\x02 \x01(\x0b\x32$.org.ffsf.demo.shoppingcart.UserCart\"x\n\x08UserCart\x12>\n\x05items\x18\x01 \x03(\x0b\x32/.org.ffsf.demo.shoppingcart.UserCart.ItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3'
)




_CARTEVENT = _descriptor.Descriptor(
  name='CartEvent',
  full_name='org.ffsf.demo.shoppingcart.CartEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='org.ffsf.demo.shoppingcart.CartEvent.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_to_cart', full_name='org.ffsf.demo.shoppingcart.CartEvent.add_to_cart', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clear_cart', full_name='org.ffsf.demo.shoppingcart.CartEvent.clear_cart', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkout', full_name='org.ffsf.demo.shoppingcart.CartEvent.checkout', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='org.ffsf.demo.shoppingcart.CartEvent.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=52,
  serialized_end=270,
)


_ADDTOCART = _descriptor.Descriptor(
  name='AddToCart',
  full_name='org.ffsf.demo.shoppingcart.AddToCart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='org.ffsf.demo.shoppingcart.AddToCart.item_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='org.ffsf.demo.shoppingcart.AddToCart.quantity', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=318,
)


_CLEARCART = _descriptor.Descriptor(
  name='ClearCart',
  full_name='org.ffsf.demo.shoppingcart.ClearCart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=331,
)


_CHECKOUT = _descriptor.Descriptor(
  name='Checkout',
  full_name='org.ffsf.demo.shoppingcart.Checkout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=343,
)


_RECEIPT = _descriptor.Descriptor(
  name='Receipt',
  full_name='org.ffsf.demo.shoppingcart.Receipt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='org.ffsf.demo.shoppingcart.Receipt.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_cart', full_name='org.ffsf.demo.shoppingcart.Receipt.user_cart', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=428,
)


_USERCART_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='org.ffsf.demo.shoppingcart.UserCart.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.ffsf.demo.shoppingcart.UserCart.ItemsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.ffsf.demo.shoppingcart.UserCart.ItemsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=550,
)

_USERCART = _descriptor.Descriptor(
  name='UserCart',
  full_name='org.ffsf.demo.shoppingcart.UserCart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='org.ffsf.demo.shoppingcart.UserCart.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USERCART_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=550,
)

_CARTEVENT.fields_by_name['add_to_cart'].message_type = _ADDTOCART
_CARTEVENT.fields_by_name['clear_cart'].message_type = _CLEARCART
_CARTEVENT.fields_by_name['checkout'].message_type = _CHECKOUT
_CARTEVENT.oneofs_by_name['event'].fields.append(
  _CARTEVENT.fields_by_name['add_to_cart'])
_CARTEVENT.fields_by_name['add_to_cart'].containing_oneof = _CARTEVENT.oneofs_by_name['event']
_CARTEVENT.oneofs_by_name['event'].fields.append(
  _CARTEVENT.fields_by_name['clear_cart'])
_CARTEVENT.fields_by_name['clear_cart'].containing_oneof = _CARTEVENT.oneofs_by_name['event']
_CARTEVENT.oneofs_by_name['event'].fields.append(
  _CARTEVENT.fields_by_name['checkout'])
_CARTEVENT.fields_by_name['checkout'].containing_oneof = _CARTEVENT.oneofs_by_name['event']
_RECEIPT.fields_by_name['user_cart'].message_type = _USERCART
_USERCART_ITEMSENTRY.containing_type = _USERCART
_USERCART.fields_by_name['items'].message_type = _USERCART_ITEMSENTRY
DESCRIPTOR.message_types_by_name['CartEvent'] = _CARTEVENT
DESCRIPTOR.message_types_by_name['AddToCart'] = _ADDTOCART
DESCRIPTOR.message_types_by_name['ClearCart'] = _CLEARCART
DESCRIPTOR.message_types_by_name['Checkout'] = _CHECKOUT
DESCRIPTOR.message_types_by_name['Receipt'] = _RECEIPT
DESCRIPTOR.message_types_by_name['UserCart'] = _USERCART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CartEvent = _reflection.GeneratedProtocolMessageType('CartEvent', (_message.Message,), {
  'DESCRIPTOR' : _CARTEVENT,
  '__module__' : 'shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.shoppingcart.CartEvent)
  })
_sym_db.RegisterMessage(CartEvent)

AddToCart = _reflection.GeneratedProtocolMessageType('AddToCart', (_message.Message,), {
  'DESCRIPTOR' : _ADDTOCART,
  '__module__' : 'shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.shoppingcart.AddToCart)
  })
_sym_db.RegisterMessage(AddToCart)

ClearCart = _reflection.GeneratedProtocolMessageType('ClearCart', (_message.Message,), {
  'DESCRIPTOR' : _CLEARCART,
  '__module__' : 'shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.shoppingcart.ClearCart)
  })
_sym_db.RegisterMessage(ClearCart)

Checkout = _reflection.GeneratedProtocolMessageType('Checkout', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUT,
  '__module__' : 'shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.shoppingcart.Checkout)
  })
_sym_db.RegisterMessage(Checkout)

Receipt = _reflection.GeneratedProtocolMessageType('Receipt', (_message.Message,), {
  'DESCRIPTOR' : _RECEIPT,
  '__module__' : 'shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.shoppingcart.Receipt)
  })
_sym_db.RegisterMessage(Receipt)

UserCart = _reflection.GeneratedProtocolMessageType('UserCart', (_message.Message,), {

  'ItemsEntry' : _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), {
    'DESCRIPTOR' : _USERCART_ITEMSENTRY,
    '__module__' : 'shopping_cart_pb2'
    # @@protoc_insertion_point(class_scope:org.ffsf.demo.shoppingcart.UserCart.ItemsEntry)
    })
  ,
  'DESCRIPTOR' : _USERCART,
  '__module__' : 'shopping_cart_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.shoppingcart.UserCart)
  })
_sym_db.RegisterMessage(UserCart)
_sym_db.RegisterMessage(UserCart.ItemsEntry)


_USERCART_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
