# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inventory.proto',
  package='org.ffsf.demo.inventory',
  syntax='proto3',
  serialized_options=b'\n!org.ffsf.demo.inventory.generatedB\020ProtobufMessagesP\000',
  serialized_pb=b'\n\x0finventory.proto\x12\x17org.ffsf.demo.inventory\"0\n\x0bRestockItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\x1f\n\x0bRequestItem\x12\x10\n\x08quantity\x18\x01 \x01(\x05\"\x90\x01\n\x10ItemAvailability\x12@\n\x06status\x18\x01 \x01(\x0e\x32\x30.org.ffsf.demo.inventory.ItemAvailability.Status\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"(\n\x06Status\x12\x0c\n\x08IN_STOCK\x10\x00\x12\x10\n\x0cOUT_OF_STOCK\x10\x01\x42\x37\n!org.ffsf.demo.inventory.generatedB\x10ProtobufMessagesP\x00\x62\x06proto3'
)



_ITEMAVAILABILITY_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='org.ffsf.demo.inventory.ItemAvailability.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IN_STOCK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUT_OF_STOCK', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=232,
  serialized_end=272,
)
_sym_db.RegisterEnumDescriptor(_ITEMAVAILABILITY_STATUS)


_RESTOCKITEM = _descriptor.Descriptor(
  name='RestockItem',
  full_name='org.ffsf.demo.inventory.RestockItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='org.ffsf.demo.inventory.RestockItem.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='org.ffsf.demo.inventory.RestockItem.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=92,
)


_REQUESTITEM = _descriptor.Descriptor(
  name='RequestItem',
  full_name='org.ffsf.demo.inventory.RequestItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantity', full_name='org.ffsf.demo.inventory.RequestItem.quantity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=125,
)


_ITEMAVAILABILITY = _descriptor.Descriptor(
  name='ItemAvailability',
  full_name='org.ffsf.demo.inventory.ItemAvailability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='org.ffsf.demo.inventory.ItemAvailability.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='org.ffsf.demo.inventory.ItemAvailability.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ITEMAVAILABILITY_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=272,
)

_ITEMAVAILABILITY.fields_by_name['status'].enum_type = _ITEMAVAILABILITY_STATUS
_ITEMAVAILABILITY_STATUS.containing_type = _ITEMAVAILABILITY
DESCRIPTOR.message_types_by_name['RestockItem'] = _RESTOCKITEM
DESCRIPTOR.message_types_by_name['RequestItem'] = _REQUESTITEM
DESCRIPTOR.message_types_by_name['ItemAvailability'] = _ITEMAVAILABILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RestockItem = _reflection.GeneratedProtocolMessageType('RestockItem', (_message.Message,), {
  'DESCRIPTOR' : _RESTOCKITEM,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.inventory.RestockItem)
  })
_sym_db.RegisterMessage(RestockItem)

RequestItem = _reflection.GeneratedProtocolMessageType('RequestItem', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTITEM,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.inventory.RequestItem)
  })
_sym_db.RegisterMessage(RequestItem)

ItemAvailability = _reflection.GeneratedProtocolMessageType('ItemAvailability', (_message.Message,), {
  'DESCRIPTOR' : _ITEMAVAILABILITY,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:org.ffsf.demo.inventory.ItemAvailability)
  })
_sym_db.RegisterMessage(ItemAvailability)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
